### PR TITLE
Db backend

### PR DESCRIPTION
**Pull request by thenomemac**
database and queue both backed by sqlite3 greatly improved performance as a result. hashing of file names

### CODE REVIEW

**Comment by matthew-sochor** [comment]
can you do a pip freeze to make a requirements?

it'll be easier to make the "required environment"

**Comment by matthew-sochor** [comment]
Not entirely sure what I'm doing wrong.  Although the networking and architecture of this project has jumped way beyond me.

I launched the app with the cli (after installing the env with the prod_install script).  App is viewable, however the scoring is on an infinite loop with no progress ever being made.

Now sure what I'm missing.

**Comment by thenomemac** [comment]
hmm we'll have to work through that infite loop but i can almost gurantee what happend is your scoring process crashed while launching. try running `tail -f logs/scoring/fish_pics.log` to see the launch log of that process

**Comment by thenomemac** [comment]
You mean for dev? The prod reqs are a bit more complex.

Ill try to get a script to reproduce the environment but not everything is
pip installable. Long run I'd like to use docker. For no I'm focused on
getting those two featues added to app around human in the loop labeling.
Can we loop at you Mac tomorrow morning to debug issues.

**Comment by matthew-sochor** [comment]
I think I figured it out, I'm missing the actual model weights...  putting those in now to see if this will run...

**Comment by thenomemac** [comment]
Fyi the code does work the environment just isn't very reproducible. The
this branch was launched via the CLI and is running in prod on the web.

**Comment by thenomemac** [comment]
Try running "source activate fisher" before running the CLI that could be
the problem

**Comment by thenomemac** [comment]
edit: `source activate fishr`

**Comment by matthew-sochor** [comment]
it was the missing weights!

**Comment by matthew-sochor** [comment]
Looks good,  There is a bug with the logging however.  It appears you may need to more specifically cast some things as strings:

```Message: 'sorted cat list:'
Arguments: (['carp', 'walleye', 'white_perch', 'yellow_perch'],)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/matthewsochor/anaconda/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/Users/matthewsochor/anaconda/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/Users/matthewsochor/anaconda/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/Users/matthewsochor/anaconda/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting```

**Comment by thenomemac** [comment]
Cool. It looks like not much is getting done but it seems to take a very
long time to figure out simple things like queues and data schema validation

**Pull request merged**
